# Generated by Django 2.1.2 on 2019-06-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称')),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('small_group', models.CharField(blank=True, choices=[('default', '无'), ('shece', '舌侧'), ('lucy', 'Lucy透明矫治器-李志鹏'), ('chunce', '唇侧计算机定位'), ('tpa', '打印TPA'), ('shececongzuo', '脱落舌侧托槽重新打印-甄浩'), ('shecezhenhao', '舌侧矫治器-甄浩'), ('baochiqi', '保持器机加工-马晨'), ('jianjie', '间接粘接-李志鹏'), ('yinshimei', '隐适美-李志鹏'), ('gongneng', '功能矫治器-韩彬羽')], max_length=20, null=True)),
                ('big_group', models.PositiveIntegerField(blank=True, choices=[(0, '状态'), (1, '要做'), (2, '已发送'), (3, '已收到'), (4, '已戴走')], null=True)),
                ('cTime', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
