# Generated by Django 2.1.2 on 2019-07-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugitem',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '缺货'), (1, '充足'), (2, '待补充'), (3, '分类1'), (4, '分类1')], null=True),
        ),
        migrations.AlterField(
            model_name='drugitem',
            name='big_group',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '分类'), (1, '分类1'), (2, '分类1'), (3, '分类1'), (4, '分类1')], null=True),
        ),
        migrations.AlterField(
            model_name='drugitem',
            name='small_group',
            field=models.CharField(blank=True, choices=[('default', '无'), ('shece', '分类1'), ('lucy', '分类1'), ('chunce', '分类1'), ('tpa', '分类1'), ('shececongzuo', '分类1'), ('shecezhenhao', '分类1'), ('baochiqi', '分类1'), ('jianjie', '分类1'), ('yinshimei', '分类1'), ('gongneng', '分类1')], max_length=20, null=True),
        ),
    ]
