# Generated by Django 2.1.2 on 2019-07-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20190726_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='event time')),
                ('count', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='count')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='price')),
                ('prop', models.CharField(choices=[('+', 'PLUS'), ('-', 'MINUS')], default='+', max_length=2, verbose_name='plus or minus property')),
                ('user', models.CharField(blank=True, max_length=12, null=True)),
                ('comment', models.CharField(blank=True, max_length=64, null=True)),
                ('drugitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.DrugItem')),
            ],
        ),
    ]
