# Generated by Django 2.1.2 on 2019-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_inoutdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugitem',
            name='shortname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='prop',
            field=models.CharField(choices=[('+', '入库'), ('-', '出库')], default='+', max_length=2, verbose_name='plus or minus property'),
        ),
    ]
