# Generated by Django 2.1.2 on 2018-12-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0010_auto_20181211_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称')),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, choices=[('shece', '舌侧'), ('lucy', 'Lucy透明矫治器-李志鹏'), ('chunce', '唇侧计算机定位'), ('tpa', '打印TPA'), ('shececongzuo', '脱落舌侧托槽重新打印-甄浩'), ('shecezhenhao', '舌侧矫治器-甄浩'), ('baochiqi', '保持器机加工-马晨'), ('jianjie', '间接粘接-李志鹏'), ('yinshimei', '隐适美-李志鹏'), ('gongneng', '功能矫治器-韩彬羽')], max_length=20, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, '要做'), (2, '已发送'), (3, '已收到'), (4, '已戴走')], null=True)),
                ('doc', models.CharField(blank=True, max_length=20, null=True)),
                ('startTime', models.DateField(auto_now_add=True, null=True)),
                ('endTime', models.DateField(null=True)),
                ('timeLength', models.CharField(blank=True, max_length=10, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='boards.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Task_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签名称')),
                ('tasks', models.ManyToManyField(related_name='tags', to='tasklist.Task')),
            ],
        ),
    ]
