# Generated by Django 2.1.2 on 2019-04-17 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0013_auto_20190408_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=16, null=True)),
                ('patientName', models.CharField(max_length=16, null=True)),
                ('startDate', models.DateField()),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('createDateTime', models.DateTimeField(blank=True)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('type', models.IntegerField(blank=True)),
                ('isFirstVisit', models.BooleanField(blank=True, null=True)),
                ('isCharged', models.BooleanField(blank=True, null=True)),
                ('isRecoded', models.BooleanField(blank=True, null=True)),
                ('isNextAppoiment', models.BooleanField(blank=True, null=True)),
                ('linkedApptID', models.IntegerField(blank=True, null=True)),
                ('isCancel', models.BooleanField(blank=True, null=True)),
                ('isCheckedIn', models.BooleanField(blank=True, null=True)),
                ('isFinished', models.BooleanField(blank=True, null=True)),
                ('isLeft', models.BooleanField(blank=True, null=True)),
                ('isConfirmed', models.BooleanField(blank=True, null=True)),
                ('isFail', models.BooleanField(blank=True, null=True)),
                ('isSeated', models.BooleanField(blank=True, null=True)),
                ('isPending', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateForAppoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='apptitem',
            name='dateForAppt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apptItems', to='appointment.DateForAppoint'),
        ),
        migrations.AddField(
            model_name='apptitem',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apptItems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apptitem',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apptItems', to='boards.Person'),
        ),
    ]
