# Generated by Django 2.1.2 on 2019-04-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20190418_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptitem',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
