# Generated by Django 2.1.2 on 2019-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20190418_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apptitem',
            old_name='isNextAppoiment',
            new_name='hasRevisit',
        ),
        migrations.AddField(
            model_name='apptitem',
            name='checkInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apptitem',
            name='checkInType',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='apptitem',
            name='isCheckedOut',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='apptitem',
            name='seatTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
