# Generated by Django 2.1.2 on 2018-10-09 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('path', models.TextField(max_length=100, null=True)),
                ('thumbnail', models.TextField(max_length=100, null=True)),
                ('isAvatar', models.NullBooleanField()),
                ('upLoadTime', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField(null=True)),
                ('comment', models.TextField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idnum', models.IntegerField(null=True)),
                ('clinic', models.CharField(max_length=20, null=True)),
                ('birth', models.DateField(null=True)),
                ('sex', models.IntegerField(null=True)),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('icon', models.TextField(max_length=100, null=True)),
                ('isEnd', models.NullBooleanField()),
                ('startDate', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('isFirst', models.NullBooleanField()),
                ('isLast', models.NullBooleanField()),
                ('type', models.IntegerField()),
                ('upLoadTime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='boards.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(related_name='tags', to='boards.Image')),
                ('persons', models.ManyToManyField(related_name='tags', to='boards.Person')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='boards.Person'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='boards.Post'),
        ),
    ]
